import React from "react";
import { Card, CardContent } from "@/components/ui/card";

export default function Terms() {
  return (
    <div className="min-h-screen p-6 md:p-8" style={{ backgroundColor: 'var(--background)' }}>
      <div className="max-w-4xl mx-auto">
        <Card className="border-0 rounded-2xl shadow-sm" style={{ backgroundColor: 'var(--card)' }}>
          <CardContent className="p-8 md:p-12">
            <h1 className="text-4xl font-bold mb-2" style={{ color: 'var(--text)' }}>
              Terms & Conditions
            </h1>
            <p className="text-sm mb-8" style={{ color: 'var(--text-muted)' }}>
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>

            <div className="space-y-6 text-base leading-relaxed" style={{ color: 'var(--text)' }}>
              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  1. Acceptance of Terms
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  By accessing and using Prism, you accept and agree to be bound by these Terms and Conditions. 
                  If you do not agree to these terms, please do not use our service.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  2. Description of Service
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  Prism is an AI-powered content creation platform that helps users generate, manage, and publish 
                  social media content. Our service includes content generation, trend analysis, visual design tools, 
                  and social media integrations.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  3. User Accounts
                </h2>
                <p className="mb-3" style={{ color: 'var(--text-muted)' }}>
                  You must create an account to use Prism. You are responsible for:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4" style={{ color: 'var(--text-muted)' }}>
                  <li>Maintaining the security of your account credentials</li>
                  <li>All activities that occur under your account</li>
                  <li>Providing accurate and complete information</li>
                  <li>Promptly notifying us of any unauthorized access</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  4. Content Ownership and License
                </h2>
                <div className="space-y-3" style={{ color: 'var(--text-muted)' }}>
                  <p>
                    <strong>Your Content:</strong> You retain all rights to content you create, upload, or input into Prism. 
                    By using our service, you grant us a limited license to process, store, and display your content 
                    solely to provide our services to you.
                  </p>
                  <p>
                    <strong>AI-Generated Content:</strong> Content generated by our AI becomes your property, and you 
                    are free to use it commercially. However, you are responsible for ensuring it complies with 
                    applicable laws and platform policies.
                  </p>
                  <p>
                    <strong>Prism Platform:</strong> All intellectual property rights in the Prism platform, including 
                    our AI models, algorithms, and design, remain our property.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  5. Acceptable Use
                </h2>
                <p className="mb-3" style={{ color: 'var(--text-muted)' }}>
                  You agree NOT to use Prism to:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4" style={{ color: 'var(--text-muted)' }}>
                  <li>Create illegal, harmful, threatening, or abusive content</li>
                  <li>Violate intellectual property rights of others</li>
                  <li>Spam, phish, or engage in fraudulent activities</li>
                  <li>Attempt to hack, reverse engineer, or compromise our service</li>
                  <li>Violate social media platform terms of service</li>
                  <li>Generate misleading or false information</li>
                  <li>Harass, bully, or harm others</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  6. Social Media Integrations
                </h2>
                <p className="mb-3" style={{ color: 'var(--text-muted)' }}>
                  When connecting social media accounts:
                </p>
                <ul className="list-disc list-inside space-y-2 ml-4" style={{ color: 'var(--text-muted)' }}>
                  <li>You must own or have permission to manage the connected accounts</li>
                  <li>You remain responsible for all content posted through Prism</li>
                  <li>You must comply with each platform's terms of service</li>
                  <li>We are not liable for actions taken by social media platforms</li>
                  <li>You can disconnect accounts at any time</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  7. AI-Generated Content Disclaimer
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  While we strive for accuracy, AI-generated content may contain errors or inaccuracies. 
                  You are responsible for reviewing and verifying all AI-generated content before publishing. 
                  Prism is not liable for any consequences resulting from the use of AI-generated content.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  8. Subscription and Payment
                </h2>
                <div className="space-y-3" style={{ color: 'var(--text-muted)' }}>
                  <p>
                    <strong>Billing:</strong> Subscription fees are billed in advance on a recurring basis. 
                    All fees are non-refundable unless required by law.
                  </p>
                  <p>
                    <strong>Cancellation:</strong> You may cancel your subscription at any time. Your access 
                    will continue until the end of your current billing period.
                  </p>
                  <p>
                    <strong>Price Changes:</strong> We may change our pricing with 30 days' notice. 
                    Changes will not affect your current billing period.
                  </p>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  9. Service Availability
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  We strive to maintain 99.9% uptime, but we do not guarantee uninterrupted service. 
                  We may perform maintenance, updates, or suspend service temporarily. We are not liable 
                  for service interruptions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  10. Limitation of Liability
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  To the maximum extent permitted by law, Prism shall not be liable for any indirect, 
                  incidental, special, or consequential damages arising from your use of our service, 
                  including but not limited to lost profits, data loss, or business interruption.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  11. Indemnification
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  You agree to indemnify and hold Prism harmless from any claims, losses, or damages 
                  arising from your use of our service, your content, or your violation of these terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  12. Termination
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  We reserve the right to suspend or terminate your account if you violate these terms 
                  or engage in fraudulent, abusive, or illegal activities. Upon termination, your right 
                  to use Prism immediately ceases.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  13. Changes to Terms
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  We may update these terms from time to time. We will notify you of significant changes 
                  via email or through our service. Continued use of Prism after changes constitutes 
                  acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  14. Governing Law
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  These terms shall be governed by and construed in accordance with the laws of your 
                  jurisdiction, without regard to conflict of law provisions.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold mb-3" style={{ color: 'var(--primary)' }}>
                  15. Contact Information
                </h2>
                <p style={{ color: 'var(--text-muted)' }}>
                  If you have questions about these terms, please contact us:
                  <br />
                  <strong>Email:</strong> legal@prism.app
                  <br />
                  <strong>Support:</strong> support@prism.app
                </p>
              </section>

              <section className="pt-6 border-t" style={{ borderColor: 'var(--border)' }}>
                <p className="text-sm italic" style={{ color: 'var(--text-muted)' }}>
                  By using Prism, you acknowledge that you have read, understood, and agree to be bound 
                  by these Terms and Conditions.
                </p>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}